-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 3fa02652357ff0dbb42b5bc78c673b7bc105fcf3
    hooks:
    -   id: trailing-whitespace
        files: \.(py|yaml|json)$
    -   id: check-json
        files: \.json$
    -   id: pretty-format-json
        args:
        - --autofix
        - --no-sort-keys
        files: \.json$
    -   id: requirements-txt-fixer
        files: requirements.*\.txt$
